id: AA82114A2
title: Aspiration at the Moment of Death
type: translation
pechas:
- IA81B02E4
- IE46677C8
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:43:27.750139
  last_modified_at: 2023-01-04 11:43:27.750151
  collections:
  - Dodrupchen Jigme Trinle Özer Series
  - Works of Tibetan Masters
alignment_to_base:
  IA81B02E4/9D1B: 6C01
  IE46677C8/46F0: 6C01
